name: social_analysis
description: A Social Analysis Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  numberpicker: ^2.1.2
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  http: ^0.13.5
  easy_localization: ^3.0.1
  photo_view: ^0.14.0
  share_plus: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/